"""Initial schema for all cells

Revision ID: 8f2597cc30e3
Revises: 
Create Date: 2026-05-02 00:29:05.082588
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2597cc30e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('spec_format', sa.String(), nullable=True),
    sa.Column('spec_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('breaking_changes', sa.Text(), nullable=True),
    sa.Column('changelog', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_contracts_service_name', 'api_contracts', ['service_name'], unique=False)
    op.create_index('ix_api_contracts_status', 'api_contracts', ['status'], unique=False)
    op.create_index('ix_api_contracts_version', 'api_contracts', ['version'], unique=False)
    op.create_table('architecture_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cell_errors_error_type', 'cell_errors', ['error_type'], unique=False)
    op.create_index('ix_cell_errors_source_interaction_id', 'cell_errors', ['source_interaction_id'], unique=False)
    op.create_index('ix_cell_errors_status', 'cell_errors', ['status'], unique=False)
    op.create_table('cell_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cell_references_category', 'cell_references', ['category'], unique=False)
    op.create_index('ix_cell_references_source_interaction_id', 'cell_references', ['source_interaction_id'], unique=False)
    op.create_table('cell_research_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cell_versions_component', 'cell_versions', ['component'], unique=False)
    op.create_index('ix_cell_versions_source_interaction_id', 'cell_versions', ['source_interaction_id'], unique=False)
    op.create_table('code_snippets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('code_content', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cve_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upgrade_to', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dependencies_ecosystem', 'dependencies', ['ecosystem'], unique=False)
    op.create_index('ix_dependencies_name', 'dependencies', ['name'], unique=False)
    op.create_index('ix_dependencies_project', 'dependencies', ['project'], unique=False)
    op.create_index('ix_dependencies_status', 'dependencies', ['status'], unique=False)
    op.create_table('design_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_made', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files_discussed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('discussion_count', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('intel_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('classification_level', sa.String(), nullable=True),
    sa.Column('tlp_level', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('analyst', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ioc_refs', sa.JSON(), nullable=True),
    sa.Column('threat_actor_refs', sa.JSON(), nullable=True),
    sa.Column('incident_refs', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('incident_refs', sa.JSON(), nullable=True),
    sa.Column('threat_actor_refs', sa.JSON(), nullable=True),
    sa.Column('classification_level', sa.String(), nullable=True),
    sa.Column('tlp_level', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_table('kill_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('threat_actor_ref', sa.String(), nullable=True),
    sa.Column('target_org', sa.String(), nullable=True),
    sa.Column('attribution_confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('phases', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('mitre_techniques', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ioc_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('incident_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('classification_level', sa.String(), nullable=True),
    sa.Column('tlp_level', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kill_chains_framework', 'kill_chains', ['framework'], unique=False)
    op.create_index('ix_kill_chains_status', 'kill_chains', ['status'], unique=False)
    op.create_index('ix_kill_chains_threat_actor_ref', 'kill_chains', ['threat_actor_ref'], unique=False)
    op.create_table('memory_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('conversation_ids', sa.JSON(), nullable=True),
    sa.Column('file_ids', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persons_name', 'persons', ['name'], unique=False)
    op.create_index('ix_persons_source_interaction_id', 'persons', ['source_interaction_id'], unique=False)
    op.create_index('ix_persons_team', 'persons', ['team'], unique=False)
    op.create_table('runbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runbooks_category', 'runbooks', ['category'], unique=False)
    op.create_index('ix_runbooks_severity', 'runbooks', ['severity'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attack_vector', sa.String(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('mitre_tactics', sa.JSON(), nullable=True),
    sa.Column('threat_actor_name', sa.String(), nullable=True),
    sa.Column('classification_level', sa.String(), nullable=True),
    sa.Column('tlp_level', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('ioc_refs', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assignee', 'tasks', ['assignee'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_project', 'tasks', ['project'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('threat_actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('sophistication', sa.String(), nullable=True),
    sa.Column('ttps', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('stix_id', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vuln_patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('vulnerable_code', sa.Text(), nullable=False),
    sa.Column('patched_code', sa.Text(), nullable=False),
    sa.Column('patch_explanation', sa.Text(), nullable=True),
    sa.Column('cve_refs', sa.JSON(), nullable=True),
    sa.Column('cwe_refs', sa.JSON(), nullable=True),
    sa.Column('owasp_refs', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_patches_category', 'vuln_patches', ['category'], unique=False)
    op.create_index('ix_vuln_patches_language', 'vuln_patches', ['language'], unique=False)
    op.create_index('ix_vuln_patches_severity', 'vuln_patches', ['severity'], unique=False)
    op.create_table('vuln_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('internal_id', sa.String(), nullable=True),
    sa.Column('cve_candidate', sa.String(), nullable=True),
    sa.Column('cwe_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('owasp_category', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('affected_versions', sa.String(), nullable=True),
    sa.Column('affected_endpoints', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(), nullable=True),
    sa.Column('attack_vector', sa.String(), nullable=True),
    sa.Column('privileges_required', sa.String(), nullable=True),
    sa.Column('user_interaction', sa.String(), nullable=True),
    sa.Column('impact_confidentiality', sa.String(), nullable=True),
    sa.Column('impact_integrity', sa.String(), nullable=True),
    sa.Column('impact_availability', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('poc_snippet_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('capture_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ioc_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('vuln_patch_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('reproduction_steps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_artifacts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('disclosure_timeline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bounty_program', sa.String(), nullable=True),
    sa.Column('program_url', sa.String(), nullable=True),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('payout_currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('classification_level', sa.String(), nullable=True),
    sa.Column('tlp_level', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retain_reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_reports_cve_candidate', 'vuln_reports', ['cve_candidate'], unique=False)
    op.create_index('ix_vuln_reports_severity', 'vuln_reports', ['severity'], unique=False)
    op.create_index('ix_vuln_reports_status', 'vuln_reports', ['status'], unique=False)
    op.create_index('ix_vuln_reports_vendor', 'vuln_reports', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vuln_reports_vendor', table_name='vuln_reports')
    op.drop_index('ix_vuln_reports_status', table_name='vuln_reports')
    op.drop_index('ix_vuln_reports_severity', table_name='vuln_reports')
    op.drop_index('ix_vuln_reports_cve_candidate', table_name='vuln_reports')
    op.drop_table('vuln_reports')
    op.drop_index('ix_vuln_patches_severity', table_name='vuln_patches')
    op.drop_index('ix_vuln_patches_language', table_name='vuln_patches')
    op.drop_index('ix_vuln_patches_category', table_name='vuln_patches')
    op.drop_table('vuln_patches')
    op.drop_table('threat_actors')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_project', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_assignee', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('security_incidents')
    op.drop_index('ix_runbooks_severity', table_name='runbooks')
    op.drop_index('ix_runbooks_category', table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_index('ix_persons_team', table_name='persons')
    op.drop_index('ix_persons_source_interaction_id', table_name='persons')
    op.drop_index('ix_persons_name', table_name='persons')
    op.drop_table('persons')
    op.drop_table('memory_sessions')
    op.drop_index('ix_kill_chains_threat_actor_ref', table_name='kill_chains')
    op.drop_index('ix_kill_chains_status', table_name='kill_chains')
    op.drop_index('ix_kill_chains_framework', table_name='kill_chains')
    op.drop_table('kill_chains')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_table('interactions')
    op.drop_table('intel_reports')
    op.drop_table('files_discussed')
    op.drop_table('design_decisions')
    op.drop_index('ix_dependencies_status', table_name='dependencies')
    op.drop_index('ix_dependencies_project', table_name='dependencies')
    op.drop_index('ix_dependencies_name', table_name='dependencies')
    op.drop_index('ix_dependencies_ecosystem', table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_table('conversations')
    op.drop_table('code_snippets')
    op.drop_index('ix_cell_versions_source_interaction_id', table_name='cell_versions')
    op.drop_index('ix_cell_versions_component', table_name='cell_versions')
    op.drop_table('cell_versions')
    op.drop_table('cell_research_questions')
    op.drop_index('ix_cell_references_source_interaction_id', table_name='cell_references')
    op.drop_index('ix_cell_references_category', table_name='cell_references')
    op.drop_table('cell_references')
    op.drop_table('cell_notes')
    op.drop_index('ix_cell_errors_status', table_name='cell_errors')
    op.drop_index('ix_cell_errors_source_interaction_id', table_name='cell_errors')
    op.drop_index('ix_cell_errors_error_type', table_name='cell_errors')
    op.drop_table('cell_errors')
    op.drop_table('architecture_notes')
    op.drop_index('ix_api_contracts_version', table_name='api_contracts')
    op.drop_index('ix_api_contracts_status', table_name='api_contracts')
    op.drop_index('ix_api_contracts_service_name', table_name='api_contracts')
    op.drop_table('api_contracts')
    # ### end Alembic commands ###
