{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace | default .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}

{{- end }}
